#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.3.0
# Generated On: 7/21/2009 2:07 PM
# Generated By: afokkema
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$button4 = New-Object System.Windows.Forms.Button
$linkLabel1 = New-Object System.Windows.Forms.LinkLabel
$checkedListBox4 = New-Object System.Windows.Forms.CheckedListBox
$checkedListBox3 = New-Object System.Windows.Forms.CheckedListBox
$label5 = New-Object System.Windows.Forms.Label
$label4 = New-Object System.Windows.Forms.Label
$button3 = New-Object System.Windows.Forms.Button
$checkedListBox2 = New-Object System.Windows.Forms.CheckedListBox
$button2 = New-Object System.Windows.Forms.Button
$label3 = New-Object System.Windows.Forms.Label
$checkedListBox1 = New-Object System.Windows.Forms.CheckedListBox
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$textBox1 = New-Object System.Windows.Forms.TextBox
$button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$button3_OnClick= 
{
#TODO: Place custom script here
	foreach($vmname in $checkedListBox1.CheckedItems)
    {
        $checkedListBox3.Items.Add($vmname)
   	}

    foreach($vmhostname in $checkedListBox2.CheckedItems)
    {
        $checkedListBox4.Items.Add($vmhostname)
	}

    [bool]$selected = $true
    for ($i = 0; $i -lt $checkedListBox3.Items.Count; $i++) { 
        $checkedListBox3.SetItemChecked( $i, $selected ) 
    } 

    [bool]$selected = $true
    for ($i = 0; $i -lt $checkedListBox4.Items.Count; $i++) { 
        $checkedListBox4.SetItemChecked( $i, $selected ) 
    } 
}

$button2_OnClick= 
{
#TODO: Place custom script here

	foreach($vm in $checkedListBox3.CheckedItems)
	{
		Get-VM -Name $vm | Move-VM -Destination (Get-VMHost $checkedListBox4.CheckedItems)
	}
		# MessageBox
		[System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
		[System.Windows.Forms.MessageBox]::Show("Selected VM's are migrated")

	$checkedListBox3.Items.Clear()
	$checkedListBox4.Items.Clear()

    [bool]$selected = $false
    for ($i = 0; $i -lt $checkedListBox1.Items.Count; $i++) { 
        $checkedListBox1.SetItemChecked( $i, $selected ) 
    } 

    [bool]$selected = $false
    for ($i = 0; $i -lt $checkedListBox2.Items.Count; $i++) { 
        $checkedListBox2.SetItemChecked( $i, $selected ) 
    } 	

}

$button4_OnClick= 
{
#TODO: Place custom script here
	
	#Disconnect from vCenter server
	Disconnect-VIServer -Confirm:$false
	
	#Close Form
	$form1.close()
}

$handler_button1_Click= 
{
#TODO: Place custom script here

if ((Get-PSSnapin "VMware.VimAutomation.Core" -ErrorAction SilentlyContinue) -eq $null) {
Add-PSSnapin "VMware.VimAutomation.Core"
} 

#Connect to vCenter
Connect-VIServer $textBox1.Text 

#Get VM's
Get-VM | % { [void]$checkedListBox1.items.add($_.Name) }

#Get VMHost (ESX Servers)
Get-VMHost | % { [void]$checkedListBox2.items.add($_.Name) }


$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}
}


#----------------------------------------------
#region Generated Form Code
$form1.Text = 'Fast vMotion'
$form1.Name = 'form1'
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 507
$System_Drawing_Size.Height = 595
$form1.ClientSize = $System_Drawing_Size

$button4.TabIndex = 19
$button4.Name = 'button4'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 23
$button4.Size = $System_Drawing_Size
$button4.UseVisualStyleBackColor = $True

$button4.Text = 'Close..'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 418
$System_Drawing_Point.Y = 554
$button4.Location = $System_Drawing_Point
$button4.DataBindings.DefaultDataSourceUpdateMode = 0
$button4.add_Click($button4_OnClick)

$form1.Controls.Add($button4)


$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 84
$System_Drawing_Size.Height = 23
$linkLabel1.Size = $System_Drawing_Size
$linkLabel1.TabIndex = 17
$linkLabel1.Text = 'www.ict-freak.nl'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 411
$System_Drawing_Point.Y = 15
$linkLabel1.Location = $System_Drawing_Point
$linkLabel1.TabStop = $True
$linkLabel1.DataBindings.DefaultDataSourceUpdateMode = 0
$linkLabel1.Name = 'linkLabel1'

$form1.Controls.Add($linkLabel1)

$checkedListBox4.FormattingEnabled = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 232
$System_Drawing_Size.Height = 94
$checkedListBox4.Size = $System_Drawing_Size
$checkedListBox4.DataBindings.DefaultDataSourceUpdateMode = 0
$checkedListBox4.Name = 'checkedListBox4'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 261
$System_Drawing_Point.Y = 413
$checkedListBox4.Location = $System_Drawing_Point
$checkedListBox4.Sorted = $True
$checkedListBox4.TabIndex = 16

$form1.Controls.Add($checkedListBox4)

$checkedListBox3.FormattingEnabled = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 231
$System_Drawing_Size.Height = 94
$checkedListBox3.Size = $System_Drawing_Size
$checkedListBox3.DataBindings.DefaultDataSourceUpdateMode = 0
$checkedListBox3.Name = 'checkedListBox3'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 413
$checkedListBox3.Location = $System_Drawing_Point
$checkedListBox3.Sorted = $True
$checkedListBox3.TabIndex = 15

$form1.Controls.Add($checkedListBox3)

$label5.TabIndex = 13
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$label5.Size = $System_Drawing_Size
$label5.Text = 'Selected ESX Host'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 324
$System_Drawing_Point.Y = 398
$label5.Location = $System_Drawing_Point
$label5.DataBindings.DefaultDataSourceUpdateMode = 0
$label5.Name = 'label5'

$form1.Controls.Add($label5)

$label4.TabIndex = 11
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$label4.Size = $System_Drawing_Size
$label4.Text = 'Selected VM''s'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 73
$System_Drawing_Point.Y = 398
$label4.Location = $System_Drawing_Point
$label4.DataBindings.DefaultDataSourceUpdateMode = 0
$label4.Name = 'label4'

$form1.Controls.Add($label4)

$button3.TabIndex = 9
$button3.Name = 'button3'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 23
$button3.Size = $System_Drawing_Size
$button3.UseVisualStyleBackColor = $True

$button3.Text = 'Select..'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 525
$button3.Location = $System_Drawing_Point
$button3.DataBindings.DefaultDataSourceUpdateMode = 0
$button3.add_Click($button3_OnClick)

$form1.Controls.Add($button3)

$checkedListBox2.FormattingEnabled = $True
$checkedListBox2.CheckOnClick = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 232
$System_Drawing_Size.Height = 304
$checkedListBox2.Size = $System_Drawing_Size
$checkedListBox2.DataBindings.DefaultDataSourceUpdateMode = 0
$checkedListBox2.Name = 'checkedListBox2'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 261
$System_Drawing_Point.Y = 85
$checkedListBox2.Location = $System_Drawing_Point
$checkedListBox2.Sorted = $True
$checkedListBox2.TabIndex = 8

$form1.Controls.Add($checkedListBox2)

$button2.TabIndex = 7
$button2.Name = 'button2'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 74
$System_Drawing_Size.Height = 23
$button2.Size = $System_Drawing_Size
$button2.UseVisualStyleBackColor = $True

$button2.Text = 'VMotion..'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 554
$button2.Location = $System_Drawing_Point
$button2.DataBindings.DefaultDataSourceUpdateMode = 0
$button2.add_Click($button2_OnClick)

$form1.Controls.Add($button2)

$label3.TabIndex = 6
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 78
$System_Drawing_Size.Height = 23
$label3.Size = $System_Drawing_Size
$label3.Text = 'Select VM''s'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 73
$System_Drawing_Point.Y = 59
$label3.Location = $System_Drawing_Point
$label3.DataBindings.DefaultDataSourceUpdateMode = 0
$label3.Name = 'label3'

$form1.Controls.Add($label3)

$checkedListBox1.FormattingEnabled = $True
$checkedListBox1.CheckOnClick = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 232
$System_Drawing_Size.Height = 304
$checkedListBox1.Size = $System_Drawing_Size
$checkedListBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$checkedListBox1.Name = 'checkedListBox1'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 85
$checkedListBox1.Location = $System_Drawing_Point
$checkedListBox1.MultiColumn = $false
$checkedListBox1.TabIndex = 5
$checkedListBox1.Sorted = $True

$form1.Controls.Add($checkedListBox1)

$label2.TabIndex = 4
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 88
$System_Drawing_Size.Height = 351
$label2.Size = $System_Drawing_Size
$label2.Text = 'Destination:'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 324
$System_Drawing_Point.Y = 59
$label2.Location = $System_Drawing_Point
$label2.DataBindings.DefaultDataSourceUpdateMode = 0
$label2.Name = 'label2'

$form1.Controls.Add($label2)

$label1.TabIndex = 2
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 87
$System_Drawing_Size.Height = 23
$label1.Size = $System_Drawing_Size
$label1.Text = 'vCenter Server:'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 12
$label1.Location = $System_Drawing_Point
$label1.DataBindings.DefaultDataSourceUpdateMode = 0
$label1.Name = 'label1'

$form1.Controls.Add($label1)

$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 152
$System_Drawing_Size.Height = 20
$textBox1.Size = $System_Drawing_Size
$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$textBox1.Name = 'textBox1'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 106
$System_Drawing_Point.Y = 12
$textBox1.Location = $System_Drawing_Point
$textBox1.TabIndex = 1

$form1.Controls.Add($textBox1)

$button1.TabIndex = 0
$button1.Name = 'button1'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 23
$button1.Size = $System_Drawing_Size
$button1.UseVisualStyleBackColor = $True

$button1.Text = 'Login..'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 264
$System_Drawing_Point.Y = 12
$button1.Location = $System_Drawing_Point
$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.add_Click($handler_button1_Click)

$form1.Controls.Add($button1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm


